import { ItemIdentifier } from "@serenityjs/core";

export default [
  //High Efficiency Fuel
  { identifier: ItemIdentifier.LavaBucket, burnTime: 20000 },
  { identifier: ItemIdentifier.CoalBlock, burnTime: 16000 },
  { identifier: ItemIdentifier.DriedKelpBlock, burnTime: 4000 },
  { identifier: ItemIdentifier.BlazeRod, burnTime: 2400 },
  { identifier: ItemIdentifier.Coal, burnTime: 1600 },
  { identifier: ItemIdentifier.Charcoal, burnTime: 1600 },

  //Boats
  { identifier: ItemIdentifier.OakBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.SpruceBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.BirchBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.JungleBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.AcaciaBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.DarkOakBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.MangroveBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.CherryBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.BambooRaft, burnTime: 1200 },

  //Boats with Chest
  { identifier: ItemIdentifier.OakChestBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.SpruceChestBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.BirchChestBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.JungleChestBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.AcaciaChestBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.DarkOakChestBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.MangroveChestBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.CherryChestBoat, burnTime: 1200 },
  { identifier: ItemIdentifier.BambooChestRaft, burnTime: 1200 },

  //Scaffolding 
  { identifier: ItemIdentifier.Scaffolding, burnTime: 400 },

  //Logs & Wood 
  { identifier: ItemIdentifier.OakLog, burnTime: 300 },
  { identifier: ItemIdentifier.SpruceLog, burnTime: 300 },
  { identifier: ItemIdentifier.BirchLog, burnTime: 300 },
  { identifier: ItemIdentifier.JungleLog, burnTime: 300 },
  { identifier: ItemIdentifier.AcaciaLog, burnTime: 300 },
  { identifier: ItemIdentifier.DarkOakLog, burnTime: 300 },
  { identifier: ItemIdentifier.MangroveLog, burnTime: 300 },
  { identifier: ItemIdentifier.CherryLog, burnTime: 300 },
  { identifier: ItemIdentifier.OakWood, burnTime: 300 },
  { identifier: ItemIdentifier.SpruceWood, burnTime: 300 },
  { identifier: ItemIdentifier.BirchWood, burnTime: 300 },
  { identifier: ItemIdentifier.JungleWood, burnTime: 300 },
  { identifier: ItemIdentifier.AcaciaWood, burnTime: 300 },
  { identifier: ItemIdentifier.DarkOakWood, burnTime: 300 },
  { identifier: ItemIdentifier.MangroveWood, burnTime: 300 },
  { identifier: ItemIdentifier.CherryWood, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedOakLog, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedSpruceLog, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedBirchLog, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedJungleLog, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedAcaciaLog, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedDarkOakLog, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedMangroveLog, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedCherryLog, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedOakWood, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedSpruceWood, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedBirchWood, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedJungleWood, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedAcaciaWood, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedDarkOakWood, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedMangroveWood, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedCherryWood, burnTime: 300 },
  { identifier: ItemIdentifier.BambooBlock, burnTime: 300 },
  { identifier: ItemIdentifier.StrippedBambooBlock, burnTime: 300 },

  //Planks 
  { identifier: ItemIdentifier.OakPlanks, burnTime: 300 },
  { identifier: ItemIdentifier.SprucePlanks, burnTime: 300 },
  { identifier: ItemIdentifier.BirchPlanks, burnTime: 300 },
  { identifier: ItemIdentifier.JunglePlanks, burnTime: 300 },
  { identifier: ItemIdentifier.AcaciaPlanks, burnTime: 300 },
  { identifier: ItemIdentifier.DarkOakPlanks, burnTime: 300 },
  { identifier: ItemIdentifier.MangrovePlanks, burnTime: 300 },
  { identifier: ItemIdentifier.CherryPlanks, burnTime: 300 },
  { identifier: ItemIdentifier.BambooPlanks, burnTime: 300 },
  { identifier: ItemIdentifier.BambooMosaic, burnTime: 300 },

  //Stairs 
  { identifier: ItemIdentifier.OakStairs, burnTime: 300 },
  { identifier: ItemIdentifier.SpruceStairs, burnTime: 300 },
  { identifier: ItemIdentifier.BirchStairs, burnTime: 300 },
  { identifier: ItemIdentifier.JungleStairs, burnTime: 300 },
  { identifier: ItemIdentifier.AcaciaStairs, burnTime: 300 },
  { identifier: ItemIdentifier.DarkOakStairs, burnTime: 300 },
  { identifier: ItemIdentifier.MangroveStairs, burnTime: 300 },
  { identifier: ItemIdentifier.CherryStairs, burnTime: 300 },
  { identifier: ItemIdentifier.BambooStairs, burnTime: 300 },
  { identifier: ItemIdentifier.BambooMosaicStairs, burnTime: 300 },

  //Trapdoors 
  { identifier: ItemIdentifier.Trapdoor, burnTime: 300 },
  { identifier: ItemIdentifier.SpruceTrapdoor, burnTime: 300 },
  { identifier: ItemIdentifier.BirchTrapdoor, burnTime: 300 },
  { identifier: ItemIdentifier.JungleTrapdoor, burnTime: 300 },
  { identifier: ItemIdentifier.AcaciaTrapdoor, burnTime: 300 },
  { identifier: ItemIdentifier.DarkOakTrapdoor, burnTime: 300 },
  { identifier: ItemIdentifier.MangroveTrapdoor, burnTime: 300 },
  { identifier: ItemIdentifier.CherryTrapdoor, burnTime: 300 },
  { identifier: ItemIdentifier.BambooTrapdoor, burnTime: 300 },

  //Fences & Gates 
  { identifier: ItemIdentifier.OakFence, burnTime: 300 },
  { identifier: ItemIdentifier.SpruceFence, burnTime: 300 },
  { identifier: ItemIdentifier.BirchFence, burnTime: 300 },
  { identifier: ItemIdentifier.JungleFence, burnTime: 300 },
  { identifier: ItemIdentifier.AcaciaFence, burnTime: 300 },
  { identifier: ItemIdentifier.DarkOakFence, burnTime: 300 },
  { identifier: ItemIdentifier.MangroveFence, burnTime: 300 },
  { identifier: ItemIdentifier.CherryFence, burnTime: 300 },
  { identifier: ItemIdentifier.BambooFence, burnTime: 300 },
  { identifier: ItemIdentifier.FenceGate, burnTime: 300 },
  { identifier: ItemIdentifier.SpruceFenceGate, burnTime: 300 },
  { identifier: ItemIdentifier.BirchFenceGate, burnTime: 300 },
  { identifier: ItemIdentifier.JungleFenceGate, burnTime: 300 },
  { identifier: ItemIdentifier.AcaciaFenceGate, burnTime: 300 },
  { identifier: ItemIdentifier.DarkOakFenceGate, burnTime: 300 },
  { identifier: ItemIdentifier.MangroveFenceGate, burnTime: 300 },
  { identifier: ItemIdentifier.CherryFenceGate, burnTime: 300 },
  { identifier: ItemIdentifier.BambooFenceGate, burnTime: 300 },

  //Pressure Plates 
  { identifier: ItemIdentifier.WoodenPressurePlate, burnTime: 300 },
  { identifier: ItemIdentifier.SprucePressurePlate, burnTime: 300 },
  { identifier: ItemIdentifier.BirchPressurePlate, burnTime: 300 },
  { identifier: ItemIdentifier.JunglePressurePlate, burnTime: 300 },
  { identifier: ItemIdentifier.AcaciaPressurePlate, burnTime: 300 },
  { identifier: ItemIdentifier.DarkOakPressurePlate, burnTime: 300 },
  { identifier: ItemIdentifier.MangrovePressurePlate, burnTime: 300 },
  { identifier: ItemIdentifier.CherryPressurePlate, burnTime: 300 },
  { identifier: ItemIdentifier.BambooPressurePlate, burnTime: 300 },

  //Blocks & Workstations 
  { identifier: ItemIdentifier.Chest, burnTime: 300 },
  { identifier: ItemIdentifier.TrappedChest, burnTime: 300 },
  { identifier: ItemIdentifier.Barrel, burnTime: 300 },
  { identifier: ItemIdentifier.Bookshelf, burnTime: 300 },
  { identifier: ItemIdentifier.ChiseledBookshelf, burnTime: 300 },
  { identifier: ItemIdentifier.Lectern, burnTime: 300 },
  { identifier: ItemIdentifier.CraftingTable, burnTime: 300 },
  { identifier: ItemIdentifier.CartographyTable, burnTime: 300 },
  { identifier: ItemIdentifier.FletchingTable, burnTime: 300 },
  { identifier: ItemIdentifier.SmithingTable, burnTime: 300 },
  { identifier: ItemIdentifier.Loom, burnTime: 300 },
  { identifier: ItemIdentifier.Composter, burnTime: 300 },
  { identifier: ItemIdentifier.Jukebox, burnTime: 300 },
  { identifier: ItemIdentifier.Noteblock, burnTime: 300 },
  { identifier: ItemIdentifier.DaylightDetector, burnTime: 300 },
  { identifier: ItemIdentifier.BeeNest, burnTime: 300 },
  { identifier: ItemIdentifier.Beehive, burnTime: 300 },
  { identifier: ItemIdentifier.Ladder, burnTime: 300 },

  //Miscellaneous
  { identifier: ItemIdentifier.FishingRod, burnTime: 300 },
  { identifier: ItemIdentifier.Bow, burnTime: 300 },
  { identifier: ItemIdentifier.Crossbow, burnTime: 300 },
  { identifier: ItemIdentifier.BrownMushroomBlock, burnTime: 300 },
  { identifier: ItemIdentifier.RedMushroomBlock, burnTime: 300 },
  { identifier: ItemIdentifier.MangroveRoots, burnTime: 300 },

  //Doors & Signs 
  { identifier: ItemIdentifier.WoodenDoor, burnTime: 200 },
  { identifier: ItemIdentifier.SpruceDoor, burnTime: 200 },
  { identifier: ItemIdentifier.BirchDoor, burnTime: 200 },
  { identifier: ItemIdentifier.JungleDoor, burnTime: 200 },
  { identifier: ItemIdentifier.AcaciaDoor, burnTime: 200 },
  { identifier: ItemIdentifier.DarkOakDoor, burnTime: 200 },
  { identifier: ItemIdentifier.MangroveDoor, burnTime: 200 },
  { identifier: ItemIdentifier.CherryDoor, burnTime: 200 },
  { identifier: ItemIdentifier.BambooDoor, burnTime: 200 },

  { identifier: ItemIdentifier.OakSign, burnTime: 200 },
  { identifier: ItemIdentifier.SpruceSign, burnTime: 200 },
  { identifier: ItemIdentifier.BirchSign, burnTime: 200 },
  { identifier: ItemIdentifier.JungleSign, burnTime: 200 },
  { identifier: ItemIdentifier.AcaciaSign, burnTime: 200 },
  { identifier: ItemIdentifier.DarkOakSign, burnTime: 200 },
  { identifier: ItemIdentifier.MangroveSign, burnTime: 200 },
  { identifier: ItemIdentifier.CherrySign, burnTime: 200 },
  { identifier: ItemIdentifier.BambooSign, burnTime: 200 },

  { identifier: ItemIdentifier.OakHangingSign, burnTime: 200 },
  { identifier: ItemIdentifier.SpruceHangingSign, burnTime: 200 },
  { identifier: ItemIdentifier.BirchHangingSign, burnTime: 200 },
  { identifier: ItemIdentifier.JungleHangingSign, burnTime: 200 },
  { identifier: ItemIdentifier.AcaciaHangingSign, burnTime: 200 },
  { identifier: ItemIdentifier.DarkOakHangingSign, burnTime: 200 },
  { identifier: ItemIdentifier.MangroveHangingSign, burnTime: 200 },
  { identifier: ItemIdentifier.CherryHangingSign, burnTime: 200 },
  { identifier: ItemIdentifier.BambooHangingSign, burnTime: 200 },

  //Wooden Tools 
  { identifier: ItemIdentifier.WoodenSword, burnTime: 200 },
  { identifier: ItemIdentifier.WoodenPickaxe, burnTime: 200 },
  { identifier: ItemIdentifier.WoodenAxe, burnTime: 200 },
  { identifier: ItemIdentifier.WoodenShovel, burnTime: 200 },
  { identifier: ItemIdentifier.WoodenHoe, burnTime: 200 },

  //Slabs 
  { identifier: ItemIdentifier.OakSlab, burnTime: 150 },
  { identifier: ItemIdentifier.SpruceSlab, burnTime: 150 },
  { identifier: ItemIdentifier.BirchSlab, burnTime: 150 },
  { identifier: ItemIdentifier.JungleSlab, burnTime: 150 },
  { identifier: ItemIdentifier.AcaciaSlab, burnTime: 150 },
  { identifier: ItemIdentifier.DarkOakSlab, burnTime: 150 },
  { identifier: ItemIdentifier.MangroveSlab, burnTime: 150 },
  { identifier: ItemIdentifier.CherrySlab, burnTime: 150 },
  { identifier: ItemIdentifier.BambooSlab, burnTime: 150 },
  { identifier: ItemIdentifier.BambooMosaicSlab, burnTime: 150 },

  //Small Items 
  { identifier: ItemIdentifier.Stick, burnTime: 100 },
  { identifier: ItemIdentifier.Bowl, burnTime: 100 },

  // Saplings
  { identifier: ItemIdentifier.OakSapling, burnTime: 100 },
  { identifier: ItemIdentifier.SpruceSapling, burnTime: 100 },
  { identifier: ItemIdentifier.BirchSapling, burnTime: 100 },
  { identifier: ItemIdentifier.JungleSapling, burnTime: 100 },
  { identifier: ItemIdentifier.AcaciaSapling, burnTime: 100 },
  { identifier: ItemIdentifier.DarkOakSapling, burnTime: 100 },
  { identifier: ItemIdentifier.MangrovePropagule, burnTime: 100 },
  { identifier: ItemIdentifier.CherrySapling, burnTime: 100 },

  // Buttons
  { identifier: ItemIdentifier.WoodenButton, burnTime: 100 },
  { identifier: ItemIdentifier.SpruceButton, burnTime: 100 },
  { identifier: ItemIdentifier.BirchButton, burnTime: 100 },
  { identifier: ItemIdentifier.JungleButton, burnTime: 100 },
  { identifier: ItemIdentifier.AcaciaButton, burnTime: 100 },
  { identifier: ItemIdentifier.DarkOakButton, burnTime: 100 },
  { identifier: ItemIdentifier.MangroveButton, burnTime: 100 },
  { identifier: ItemIdentifier.CherryButton, burnTime: 100 },
  { identifier: ItemIdentifier.BambooButton, burnTime: 100 },

  //Misc Small
  { identifier: ItemIdentifier.Bamboo, burnTime: 50 },
];