import { ItemIdentifier } from "@serenityjs/core";

export default [
  //Ores
  { input: ItemIdentifier.IronOre, output: ItemIdentifier.IronIngot },
  { input: ItemIdentifier.DeepslateIronOre, output: ItemIdentifier.IronIngot },
  { input: ItemIdentifier.RawIron, output: ItemIdentifier.IronIngot },

  { input: ItemIdentifier.GoldOre, output: ItemIdentifier.GoldIngot },
  { input: ItemIdentifier.DeepslateGoldOre, output: ItemIdentifier.GoldIngot },
  { input: ItemIdentifier.RawGold, output: ItemIdentifier.GoldIngot },

  { input: ItemIdentifier.CopperOre, output: ItemIdentifier.CopperIngot },
  { input: ItemIdentifier.DeepslateCopperOre, output: ItemIdentifier.CopperIngot },
  { input: ItemIdentifier.RawCopper, output: ItemIdentifier.CopperIngot },

  { input: ItemIdentifier.AncientDebris, output: ItemIdentifier.NetheriteScrap },
  { input: ItemIdentifier.NetherGoldOre, output: ItemIdentifier.GoldIngot },

  { input: ItemIdentifier.QuartzOre, output: ItemIdentifier.Quartz },
  { input: ItemIdentifier.RedstoneOre, output: ItemIdentifier.Redstone },
  { input: ItemIdentifier.DeepslateRedstoneOre, output: ItemIdentifier.Redstone },
  { input: ItemIdentifier.CoalOre, output: ItemIdentifier.Coal },
  { input: ItemIdentifier.DeepslateCoalOre, output: ItemIdentifier.Coal },
  { input: ItemIdentifier.EmeraldOre, output: ItemIdentifier.Emerald },
  { input: ItemIdentifier.DeepslateEmeraldOre, output: ItemIdentifier.Emerald },
  { input: ItemIdentifier.LapisOre, output: ItemIdentifier.LapisLazuli },
  { input: ItemIdentifier.DeepslateLapisOre, output: ItemIdentifier.LapisLazuli },
  { input: ItemIdentifier.DiamondOre, output: ItemIdentifier.Diamond },
  { input: ItemIdentifier.DeepslateDiamondOre, output: ItemIdentifier.Diamond },

  //Food
  { input: ItemIdentifier.Beef, output: ItemIdentifier.CookedBeef },
  { input: ItemIdentifier.Chicken, output: ItemIdentifier.CookedChicken },
  { input: ItemIdentifier.Mutton, output: ItemIdentifier.CookedMutton },
  { input: ItemIdentifier.Porkchop, output: ItemIdentifier.CookedPorkchop },
  { input: ItemIdentifier.Rabbit, output: ItemIdentifier.CookedRabbit },
  { input: ItemIdentifier.Cod, output: ItemIdentifier.CookedCod },
  { input: ItemIdentifier.Salmon, output: ItemIdentifier.CookedSalmon },
  { input: ItemIdentifier.Potato, output: ItemIdentifier.BakedPotato },
  { input: ItemIdentifier.Kelp, output: ItemIdentifier.DriedKelp },

  //Blocks
  { input: ItemIdentifier.Sand, output: ItemIdentifier.Glass },
  { input: ItemIdentifier.RedSand, output: ItemIdentifier.Glass },
  { input: ItemIdentifier.Cobblestone, output: ItemIdentifier.Stone },
  { input: ItemIdentifier.Stone, output: ItemIdentifier.SmoothStone },
  { input: ItemIdentifier.Basalt, output: ItemIdentifier.SmoothBasalt },
  { input: ItemIdentifier.QuartzBlock, output: ItemIdentifier.SmoothQuartz },
  { input: ItemIdentifier.Sandstone, output: ItemIdentifier.SmoothSandstone },
  { input: ItemIdentifier.RedSandstone, output: ItemIdentifier.SmoothRedSandstone },
  { input: ItemIdentifier.Netherrack, output: ItemIdentifier.NetherBrick },
  { input: ItemIdentifier.ClayBall, output: ItemIdentifier.Brick },
  { input: ItemIdentifier.Clay, output: ItemIdentifier.HardenedClay },
  { input: ItemIdentifier.Cactus, output: ItemIdentifier.GreenDye },
  { input: ItemIdentifier.StoneBricks, output: ItemIdentifier.CrackedStoneBricks },
  { input: ItemIdentifier.NetherBrick, output: ItemIdentifier.CrackedNetherBricks },
  { input: ItemIdentifier.DeepslateBricks, output: ItemIdentifier.CrackedDeepslateBricks },
  { input: ItemIdentifier.DeepslateTiles, output: ItemIdentifier.CrackedDeepslateTiles },
  { input: "minecraft:wet_sponge", output: ItemIdentifier.Sponge },

  //Misc
  { input: ItemIdentifier.OakLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.SpruceLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.BirchLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.JungleLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.AcaciaLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.DarkOakLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.CherryLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.MangroveLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.StrippedOakLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.StrippedSpruceLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.StrippedBirchLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.StrippedJungleLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.StrippedAcaciaLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.StrippedDarkOakLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.StrippedCherryLog, output: ItemIdentifier.Charcoal },
  { input: ItemIdentifier.StrippedMangroveLog, output: ItemIdentifier.Charcoal },

  { input: ItemIdentifier.SeaPickle, output: ItemIdentifier.LimeDye },
  { input: ItemIdentifier.ChorusFruit, output: ItemIdentifier.PoppedChorusFruit },

  // --- Armor & Tools Recycling ---
  { input: ItemIdentifier.ChainmailHelmet, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.ChainmailLeggings, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.ChainmailBoots, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.ChainmailChestplate, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronShovel, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronPickaxe, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronAxe, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronHoe, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronSword, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronHelmet, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronLeggings, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronBoots, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronChestplate, output: ItemIdentifier.IronNugget },
  { input: ItemIdentifier.IronHorseArmor, output: ItemIdentifier.IronNugget },

  { input: ItemIdentifier.GoldenHorseArmor, output: ItemIdentifier.GoldNugget },
  { input: ItemIdentifier.GoldenHelmet, output: ItemIdentifier.GoldNugget },
  { input: ItemIdentifier.GoldenLeggings, output: ItemIdentifier.GoldNugget },
  { input: ItemIdentifier.GoldenBoots, output: ItemIdentifier.GoldNugget },
  { input: ItemIdentifier.GoldenChestplate, output: ItemIdentifier.GoldNugget },
  { input: ItemIdentifier.GoldenHoe, output: ItemIdentifier.GoldNugget },
  { input: ItemIdentifier.GoldenPickaxe, output: ItemIdentifier.GoldNugget },
  { input: ItemIdentifier.GoldenShovel, output: ItemIdentifier.GoldNugget },
  { input: ItemIdentifier.GoldenSword, output: ItemIdentifier.GoldNugget },
  { input: ItemIdentifier.GoldenAxe, output: ItemIdentifier.GoldNugget },

  { input: ItemIdentifier.CopperAxe, output: "minecraft:copper_nugget" as ItemIdentifier },
  { input: ItemIdentifier.CopperBoots, output: "minecraft:copper_nugget" as ItemIdentifier },
  { input: ItemIdentifier.CopperChestplate, output: "minecraft:copper_nugget" as ItemIdentifier },
  { input: ItemIdentifier.CopperHoe, output: "minecraft:copper_nugget" as ItemIdentifier },
  { input: ItemIdentifier.CopperHelmet, output: "minecraft:copper_nugget" as ItemIdentifier },
  { input: ItemIdentifier.CopperLeggings, output: "minecraft:copper_nugget" as ItemIdentifier },
  { input: ItemIdentifier.CopperPickaxe, output: "minecraft:copper_nugget" as ItemIdentifier },
  { input: ItemIdentifier.CopperShovel, output: "minecraft:copper_nugget" as ItemIdentifier },
  { input: ItemIdentifier.CopperSword, output: "minecraft:copper_nugget" as ItemIdentifier }
];